---
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
    - bundle exec rubocop

# rspec:
#   stage: test
#   cache:
#     policy: pull
#   script:
#   - rspec spec

push image:
  stage: deploy
  when: manual
  script:
    - make publish

deploy:
  stage: deploy
  environment: production
  when: manual
  script:
    - make deploy
