---
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

rubocop:
  script:
    - gem install rubocop -N
    - rubocop

# rspec:
#   stage: test
#   cache:
#     policy: pull
#   before_script:
#     - gem install bundler  --no-ri --no-rdoc
#     - bundle install -j $(nproc) --path vendor
#   script:
#     - rspec spec

push image:
  stage: deploy
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh", "-c"]  # For Docker <= 17.03
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /root/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile $DOCKER_PROXY --destination $CI_REGISTRY_IMAGE
  only:
    - master

deploy:
  stage: deploy
  environment: production
  when: manual
  image: lachlanevenson/k8s-kubectl
  before_script: []
  script:
    - kubectl label deployment lunchplaner app=$CI_ENVIRONMENT_SLUG --overwrite
    - 'export PREVID=$(kubectl get pods -l "app=$CI_ENVIRONMENT_SLUG" -o name)'
    - 'echo "Prev: ${PREVID}"'
    - 'kubectl scale --replicas=2 deployment lunchplaner'
    - 'sleep 1'
    - 'while [ $(kubectl get pods -l "app=$CI_ENVIRONMENT_SLUG" -o custom-columns=name:metadata.name,status:status.phase | tail -n+2 | grep Running | wc -l) -lt 2 ]; do sleep 5; done'
    - 'kubectl delete ${PREVID}'
    - 'sleep 1'
    - 'kubectl scale --replicas=1 deployment lunchplaner'
  only:
    - master
