---
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
    - bundle exec rubocop

# rspec:
#   stage: test
#   cache:
#     policy: pull
#   script:
#   - rspec spec

push image:
  stage: deploy
  when: manual
  image: docker:dind
  before_script: []
  script:
    - make publish

deploy:
  stage: deploy
  environment: production
  when: manual
  image: lachlanevenson/k8s-kubectl
  before_script: []
  script:
    - PREVID=$(kubectl get pods -l "app=lunch" -o name)
    - echo "Prev: ${PREVID}"
    - kubectl scale --replicas=2 deployment lunchplaner
    - while [ $(kubectl get pods -l "app=lunch" -o custom-columns=name:metadata.name,status:status.phase | tail -n+2 | grep Running | wc -l) -lt 2 ]; do sleep 5; done
    - kubectl delete ${PREVID}
    - kubectl scale --replicas=1 deployment lunchplaner
