---
AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - '*.spec'
    - 'Rakefile'
    - 'vendor/**/*'
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 190

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
    - 'app/controllers/concerns/foreman/**/*'
